server:
  port: ${PORT:0}    #default port where the service will be started
 
eureka:  
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
      
      
      
 
spring:     
  application:
    name: student-service   #current service name to be used by the eureka server

logging:
  level:
    com.example.howtodoinjava: DEBUG